name: DingDing notify

on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - .vscode

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: DingDing notify only Push
        uses: zcong1993/actions-ding@master
        if: |
          always() &&
          github.event_name == 'push' &&
          github.repository == 'qxy-fe/configs'
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "${{ github.repository }} 仓库推送成功",
                "text": "![Random Picture](https://picsum.photos/400/200) \n GitHub 仓库 ${{ github.repository }} 推送成功。\n - [查看文档](https://qxy-fe.github.io/fe-docs/utils-lib/eslint.html) \n - [查看仓库](https://github.com/${{ github.repository }})"
              }
            }
      - name: DingDing notify only PR
        uses: zcong1993/actions-ding@master
        if: |
          always() &&
          github.event_name == 'pull_request' &&
          github.repository == 'qxy-fe/configs'
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "${{ github.repository }} 仓库合并 PR 成功",
                "text": "![Random Picture](https://picsum.photos/400/200) \n GitHub 仓库 ${{ github.repository }} 成功合并 PR - ${{ github.event.pull_request.title }}。 \n - [查看文档](https://qxy-fe.github.io/fe-docs/utils-lib/eslint.html) \n - [查看仓库](https://github.com/${{ github.repository }})"
              }
            }
