name: DingDing notify

on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - .vscode

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: DingDing notify only Push
        uses: zcong1993/actions-ding@master
        if: |
          always() &&
          github.event_name == 'push' &&
          github.repository == 'qxy-fe/configs'
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          body: |
            {
              "msgtype": "actionCard",
              "actionCard": {
                "title": "${{ github.repository }} 仓库推送成功",
                "text": "GitHub 仓库 ${{ github.repository }} 推送成功。",
                "btnOrientation": "0",
                "btns": [
                  {
                    "title": "查看仓库",
                    "actionURL": "https://github.com/${{ github.repository }}"
                  },
                  {
                    "title": "查看文档",
                    "actionURL": "https://fe-docs.goyfe.com/utils-lib/eslint.html"
                  }
                ]
              }
            }
      - name: DingDing notify only PR
        uses: zcong1993/actions-ding@master
        if: |
          always() &&
          github.event_name == 'pull_request' &&
          github.repository == 'qxy-fe/configs'
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "${{ github.repository }} 仓库合并 PR 成功",
                "text": "GitHub 仓库${{ github.repository }} 成功合并 PR - ${{ github.event.pull_request.title }}。"
                "btnOrientation": "0",
                "btns": [
                  {
                    "title": "查看仓库",
                    "actionURL": "https://github.com/${{ github.repository }}"
                  },
                  {
                    "title": "查看文档",
                    "actionURL": "https://fe-docs.goyfe.com/utils-lib/eslint.html"
                  }
                ]
              }
            }
